#!/usr/bin/env ruby

require 'socket'

TIMEOUT = 2
PORT_LIST = [21,22,23,25,53,80,443,3306,5601,8080]
DOMAIN = ARGV[0]

def scan_port(port)
  socket = Socket.new(:AF_INET, :SOCK_STREAM, 0)
  remote_addr = Socket.sockaddr_in(port, DOMAIN)

  begin
    socket.connect_nonblock(remote_addr)
  rescue Errno::EINPROGRESS
  rescue Errno::EAFNOSUPPORT
    puts 'not supported'
  end

  _, sockets, _ = IO.select(nil, [socket], nil, TIMEOUT)

  if sockets 
    p "Port #{port} is open."
  else
    p "Port #{port} is closed."
  end
end

if ARGV[0].nil?
  puts 'Please specify a domain as parameter'
  exit(0)
end

PORT_LIST.each do |port|
  scan_port(port)
end
