#!/usr/bin/env ruby

# Copyright [2021] [sum.cumo Sapiens GmbH]

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# frozen_string_literal: true

require_relative 'lib/parser'
require_relative 'lib/scanner'
require_relative 'lib/exceptions'
require_relative 'lib/configuration_reader'

puts "Most simplistic port scanner. Get help with -h\n"

if ARGV[0].nil? 
  raise MissingOptions.new
  exit(0)
else
  params = Parser.execute

  puts "WARNING: some domain owners see port scanning as a threat! Be sure, that you\n"
  puts "have the permission to scan the ports\n\n"
  print "I understand the warning and have permission to scan the ports (yes | no): "
  permission = gets.chomp

  if permission != "yes"
    exit(0)
  end

  puts "\nReading the configuration and parameters ...\n\n"

  if params.class == Params && !params.json_from_file.nil?
    puts "Domain:\t\t #{params.json_from_file["domain_name"]}"
    puts "Ports:\t\t #{params.json_from_file["ports"]}"
    puts "Timeout:\t #{params.json_from_file["timeout"]}\n\n"
  end
  sleep(2)
  
  puts "Starting the scan now ...\n\n"
  puts "------------- results -------------"
  scanner = Scanner.new(params)
  scanner.execute  
  puts "--------------- end ---------------"
end
